import type { Metadata } from "next";
import { Archivo, Fraunces, Bricolage_Grotesque } from 'next/font/google';
import "./globals.css";

// Call and assign font loaders to consts in the module scope
const archivo = Archivo({ subsets: ["latin"] });
const fraunces = Fraunces({ subsets: ["latin"] });
const bricolage = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mastermind Women and Children",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={archivo.className}>{children}</body>
    </html>
  );
}
