import type { Metadata } from "next";
import { Archivo, Fraunces, Bricolage_Grotesque  } from 'next/font/google';
import "./globals.css";

const inter = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mastermind Women and Children",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
